sudo: required

language: bash
services: docker

env:
  - DOCKER_IMAGE=nginx-rtmp

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t ${DOCKER_IMAGE} .
  - docker images
  - docker tag ${DOCKER_IMAGE} $DOCKER_USERNAME/${DOCKER_IMAGE}
  - docker push $DOCKER_USERNAME/${DOCKER_IMAGE}

after_script:
  - docker images
  - docker run -d -p 1935:1935 -p 8080:80 -t ${DOCKER_IMAGE}
  - docker ps -a
